name: Todo App Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
    - name: Cloning project
      uses: actions/checkout@v2
    - name: List files
      run: |
        ls ${{ github.workspace }}
    - name: Setup Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install project
      run: npm install
    - name: Test project
      run: npm test
    # - name: Build docker image
    #  run: sudo docker image build -t sdc:todo .
    # - name: Tag docker image
    #  run: sudo docker image tag sdc:todo ravennaras/sdc:todo
    # - name: Push docker image
    #   run: sudo docker image push ravennaras/sdc:todo
    - name: Pull docker image
      run: docker pull ravennaras/sdc:todo
    - name: Run docker container
      run: docker run -d ravennaras/sdc:todo
